apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: prints
  labels:
    name: debug
    project: prints
spec:
  containers:
  - name: debug
    image: peruripramod/debug:v1
    imagePullPolicy: Always