apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: prints
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/user"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  Namespace: prints
  # these are replica set labels
  labels:
    project: prints
    componenet: user
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: prints
      componenet: user
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: prints
        componenet: user
        tier: backend
    spec:
      containers:
      - name: user
        image: peruripramod/user
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
             name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodseconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodseconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: prints
spec:
  selector:
    project: prints
    componenet: user
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080